---
image: ubuntu:latest


stages:
    - compile
    - quiz


wherami:
    stage: compile
    script: env; echo $PWD; whereis make;

compile:
    stage: compile
    before_script:
        - apt-get update && apt-get install -y --no-install-recommends
          texlive-extra-utils
          texlive-fonts-recommended
          texlive-latex-recommended
          tex4ht
          tidy
          make
    script: make epub ps pdf dvi
    artifacts:
        paths:
            - ./

check:
   stage: quiz
   #   before_script:
   #       - apt-get update && apt-get install -y --no-install-recommends
   #          bash 
   script: ./test.sh
#
# benchmarking
# performance
# memory
# code coverage
# test coverage
